#!/bin/bash
##
## ARCHIVAL DATA INGEST SCRIPT - INITIAL DATA INGEST
##
## This script should be used when you receive data
## (a hard drive, a download, etc)
## that needs to be moved into the Archive NAS
## you expect to receive more data related to this specific event/exhibition/project
##
## If additional forbidden characters/emojis are found to be used,
## adding extra lines to this script is super simple--
## just use the same format as below substituting in that specific character.
##
## Before executing this script,
## cd into the location on the hard drive or folder where the new data is.
##
## After executing this script, use
## rsync -aiv
## to move this data into
## the appropriate location on the Archive NAS.
##
## The script performs the following actions:
##### 1. Removes certain temporary/invisible files with no archival significance
##### 2. Changes forbidden characters to dashes (-)
##### 3. Runs a quick (not exhaustive) virus scan
##
## - written by ft, March-April 2019
## - updated by mr, 2024
##

tag -r Red,Orange,Yellow,Green,Blue,Purple,Gray "$dir"
find "$dir" -type f \( -iname ".DS_Store" -o -iname "thumbs.db" -o -iname "\~\$*" \) -exec rm -rf {} \;
find "$dir" -name "*:*" -exec rename 's/:/-/g' {} +
find "$dir" -name "*🎆*" -exec rename 's/🎆/-/g' {} +
find "$dir" -name "*👍*" -exec rename 's/👍/-/g' {} +
find "$dir" -name "*🙏*" -exec rename 's/🙏/-/g' {} +
find "$dir" -name "*👌*" -exec rename 's/👌/-/g' {} +
find "$dir" -name "*🛄*" -exec rename 's/🛄/-/g' {} +
find "$dir" -name "*\|*" -exec rename 's/\|/-/g' {} +
find "$dir" -name "*\"*" -exec rename 's/\"/-/g' {} +
find "$dir" -name "*\**" -exec rename 's/\*/-/g' {} +
find "$dir" -name "*\?*" -exec rename 's/\?/-/g' {} +
find "$dir" -name "*\#*" -exec rename 's/\#/-/g' {} +
find "$dir" -name '*\\*' -exec rename 's/\\/-/g' {} +
find "$dir" -name "*~*" -exec rename 's/~/-/g' {} +
find "$dir" -name "*\`*" -exec rename 's/\`/-/g' {} +
find "$dir" -name "*@*" -exec rename 's/@/-/g' {} +
find "$dir" -name "*\$*" -exec rename 's/\$/-/g' {} +
find "$dir" -name "*%*" -exec rename 's/%/-/g' {} +
find "$dir" -name "*\^*" -exec rename 's/\^/-/g' {} +
find "$dir" -name "*&*" -exec rename 's/&/-/g' {} +
find "$dir" -name "*\>*" -exec rename 's/\>/-/g' {} +
find "$dir" -name "*\<*" -exec rename 's/\</-/g' {} +
find "$dir" -name "*:*" -exec rename 's/:/-/g' {} +
find "$dir" -name "*🎆*" -exec rename 's/🎆/-/g' {} +
find "$dir" -name "*👍*" -exec rename 's/👍/-/g' {} +
find "$dir" -name "*🙏*" -exec rename 's/🙏/-/g' {} +
find "$dir" -name "*👌*" -exec rename 's/👌/-/g' {} +
find "$dir" -name "*🛄*" -exec rename 's/🛄/-/g' {} +
find "$dir" -name "*\|*" -exec rename 's/\|/-/g' {} +
find "$dir" -name "*\"*" -exec rename 's/\"/-/g' {} +
find "$dir" -name "*\**" -exec rename 's/\*/-/g' {} +
find "$dir" -name "*\?*" -exec rename 's/\?/-/g' {} +
find "$dir" -name "*\#*" -exec rename 's/\#/-/g' {} +
find "$dir" -name '*\\*' -exec rename 's/\\/-/g' {} +
find "$dir" -name "*~*" -exec rename 's/~/-/g' {} +
find "$dir" -name "*\`*" -exec rename 's/\`/-/g' {} +
find "$dir" -name "*@*" -exec rename 's/@/-/g' {} +
find "$dir" -name "*\$*" -exec rename 's/\$/-/g' {} +
find "$dir" -name "*%*" -exec rename 's/%/-/g' {} +
find "$dir" -name "*\^*" -exec rename 's/\^/-/g' {} +
find "$dir" -name "*&*" -exec rename 's/&/-/g' {} +
find "$dir" -name "*\>*" -exec rename 's/\>/-/g' {} +
find "$dir" -name "*\<*" -exec rename 's/\</-/g' {} +

freshclam
clamscan -ir "$dir"
echo "Final ingest and bagging script complete! :)"
